# Site Author
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Huseyin Ugur Yildiz"
  pronouns         : "he/him"  
  bio              : "Associate Professor | IEEE Senior Member | Network Optimization & Wireless Communications"
  location         : "Ankara, Turkey"
  employer         : "TED University"
  uri              : "https://www.huguryildiz.com"
  email            : "hugur.yildiz@tedu.edu.tr" 

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=[YOUR_SCHOLAR_ID]"
  orcid            : "https://orcid.org/0000-0002-1556-2634"
  researchgate     : "https://www.researchgate.net/profile/Huseyin-Yildiz"

  # Repositories
  github           : "huguryildiz"
  
  # Social media
  linkedin         : "huguryildiz"